/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.controleorcamento.formularios;

import br.com.controleorcamento.atividades.AnaliseSalvar;
import br.com.controleorcamento.atividades.ConexaoMySQL;
import br.com.controleorcamento.objeto.Analise;
import br.com.controleorcamento.objeto.BdgAcum;
import br.com.controleorcamento.objeto.DataHoje;
import br.com.controleorcamento.objeto.RealAcum;
import br.com.controleorcamento.objeto.UsuarioLogado;
import java.awt.Color;
import java.awt.Component;
import java.awt.Toolkit;
import java.math.RoundingMode;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author rosaan
 */
public class AnaliseOrcamento extends javax.swing.JFrame {

    /**
     * Creates new form AnaliseOrcamento
     */
    public AnaliseOrcamento() {
        initComponents();
        selmes();
        carregarRegiao();
        carregarFilial();
        carregarMagnitude();
        carregarCentroCusto();
        carregarContaC();
        carregarArea();
        acesso();
        filtrar();
        filtrarAnalise();
        setIcon();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaOrcamento = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cBoxMagnitude = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cBoxRegiao = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cBoxFilial = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cBoxCentroCusto = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cBoxConta = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        bLimpar = new javax.swing.JButton();
        lID = new javax.swing.JLabel();
        cBoxMes = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cBoxTipoOrcamento = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        bFiltrar = new javax.swing.JButton();
        bInserir = new javax.swing.JButton();
        cBoxPlataforma = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        lNumeroAnalises = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listAnalises = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cBoxNomeUsuario = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        cBoxPreJustificativa = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lOrcadoMes = new javax.swing.JLabel();
        lRealMes = new javax.swing.JLabel();
        lDiferencaMes = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lOrcadoAcum = new javax.swing.JLabel();
        lRealAcum = new javax.swing.JLabel();
        lDiferencaAcum = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lAnaliseConta = new javax.swing.JLabel();
        lAnaliseCentro = new javax.swing.JLabel();
        lAnaliseMagnitude = new javax.swing.JLabel();
        lAnaliseFilial = new javax.swing.JLabel();
        lAnaliseRegiao = new javax.swing.JLabel();
        lAnalisePlataforma = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cBoxArea = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabelaOrcamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Plataforma", "Região", "Centro de Custo", "Descrição C.C.", "Filial", "Magnitude", "Conta", "Descrição da Conta", "BDG Mês", "Real Mês", "Diferença Mês", "BDG Acum", "Real Acum", "Diferença Acum"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, true, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaOrcamento.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tabelaOrcamento.setSelectionForeground(new java.awt.Color(51, 153, 255));
        tabelaOrcamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaOrcamentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaOrcamento);
        if (tabelaOrcamento.getColumnModel().getColumnCount() > 0) {
            tabelaOrcamento.getColumnModel().getColumn(0).setPreferredWidth(30);
        }

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/controleorcamento/imagens/icons8-Caro 2-16.png"))); // NOI18N
        jLabel1.setText("Consulta Orçamento");

        jLabel2.setText("Magnitude");

        cBoxMagnitude.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cBoxMagnitudePopupMenuWillBecomeVisible(evt);
            }
        });
        cBoxMagnitude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxMagnitudeActionPerformed(evt);
            }
        });

        jLabel3.setText("Região");

        cBoxRegiao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxRegiaoActionPerformed(evt);
            }
        });

        jLabel4.setText("Filial");

        cBoxFilial.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cBoxFilialPopupMenuWillBecomeVisible(evt);
            }
        });
        cBoxFilial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxFilialActionPerformed(evt);
            }
        });

        jLabel5.setText("Centro de Custo");

        cBoxCentroCusto.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cBoxCentroCustoPopupMenuWillBecomeVisible(evt);
            }
        });
        cBoxCentroCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxCentroCustoActionPerformed(evt);
            }
        });

        jLabel6.setText("Conta");

        cBoxConta.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cBoxContaPopupMenuWillBecomeVisible(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("INSERIR ANÁLISE");
        jScrollPane2.setViewportView(jTextArea1);

        bLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/controleorcamento/imagens/icons8-Vassoura-16.png"))); // NOI18N
        bLimpar.setText("Limpar");
        bLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimparActionPerformed(evt);
            }
        });

        cBoxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JAN", "FEV", "MAR", "ABR", "MAI", "JUN", "JUL", "AGO", "SET", "OUT", "NOV", "DEZ" }));
        cBoxMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxMesActionPerformed(evt);
            }
        });

        jLabel7.setText("Mês");

        jLabel8.setText("Orçamento");

        cBoxTipoOrcamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BDG", "RFC" }));
        cBoxTipoOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxTipoOrcamentoActionPerformed(evt);
            }
        });

        bFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/controleorcamento/imagens/icons8-Filtro-16.png"))); // NOI18N
        bFiltrar.setText("Filtrar");
        bFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFiltrarActionPerformed(evt);
            }
        });

        bInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/controleorcamento/imagens/icons8-Salvar-16.png"))); // NOI18N
        bInserir.setText("Inserir Análise");
        bInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInserirActionPerformed(evt);
            }
        });

        cBoxPlataforma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "MILHO", "SOJA" }));

        jLabel10.setText("Plataforma");

        lNumeroAnalises.setText("0");

        jLabel16.setText("Análises Cadastradas:");

        listAnalises.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listAnalisesMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(listAnalises);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setText("Vincular Responsável para Resposta de Análise");

        cBoxNomeUsuario.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cBoxNomeUsuarioPopupMenuWillBecomeVisible(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cBoxNomeUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cBoxNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel17.setText("Tipo de Justificativa");

        cBoxPreJustificativa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Bonus", "Cancelamentos Extemporâneos", "Dentro do Orçamento Anual", "Desligamento de Profissional", "Encargos", "Horas Extras", "Multa", "Orçamento Subestimado", "Orçamento Superestimado", "Reclassificação", "Sem Orçamento", "Viagem", "" }));
        cBoxPreJustificativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxPreJustificativaActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel15.setText("Informações");

        jLabel14.setText("Valor Orçado");

        jLabel11.setText("Valor Real");

        jLabel20.setText("Diferença");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Mês");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lOrcadoMes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lOrcadoMes.setText("Valor Orçado");

        lRealMes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lRealMes.setText("Valor Real");

        lDiferencaMes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lDiferencaMes.setText("Diferença");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Acumulado");

        lOrcadoAcum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lOrcadoAcum.setText("Valor Orçado");

        lRealAcum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lRealAcum.setText("Valor Real");

        lDiferencaAcum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lDiferencaAcum.setText("Diferença");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lRealMes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lOrcadoMes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lDiferencaMes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lOrcadoAcum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lRealAcum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lDiferencaAcum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lOrcadoMes)
                    .addComponent(lOrcadoAcum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lRealMes)
                    .addComponent(lRealAcum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(lDiferencaMes)
                    .addComponent(lDiferencaAcum))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lOrcadoMes.getAccessibleContext().setAccessibleDescription("");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lAnaliseConta.setText("-");

        lAnaliseCentro.setText("-");

        lAnaliseMagnitude.setText("-");

        lAnaliseFilial.setText("-");

        lAnaliseRegiao.setText("-");

        lAnalisePlataforma.setText("-");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lAnaliseRegiao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lAnaliseFilial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lAnaliseMagnitude, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lAnaliseCentro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lAnaliseConta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lAnalisePlataforma, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lAnalisePlataforma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lAnaliseRegiao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lAnaliseFilial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lAnaliseMagnitude)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lAnaliseCentro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lAnaliseConta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel18.setText("Campo para inserir análise");

        jLabel19.setText("Área");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 17, Short.MAX_VALUE)
                                .addComponent(bLimpar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bFiltrar))
                            .addComponent(cBoxRegiao, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cBoxFilial, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cBoxMagnitude, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cBoxCentroCusto, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cBoxConta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cBoxPlataforma, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cBoxPreJustificativa, 0, 247, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 13, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lNumeroAnalises, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(cBoxTipoOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(cBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cBoxArea, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lID))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1))
                            .addComponent(lID))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cBoxArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(cBoxTipoOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(lNumeroAnalises)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bInserir)
                                    .addComponent(cBoxPreJustificativa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cBoxPlataforma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cBoxRegiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cBoxFilial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cBoxMagnitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(cBoxCentroCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cBoxConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bLimpar)
                                    .addComponent(bFiltrar)))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimparActionPerformed
        limparParte();
        filtrarAnalise();
    }//GEN-LAST:event_bLimparActionPerformed

    private void tabelaOrcamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaOrcamentoMouseClicked
        DecimalFormat df = new DecimalFormat("###,###,###,##0.00");
        df.setRoundingMode(RoundingMode.UP);

        if (tabelaOrcamento.getSelectedRow() != -1) {
            lID.setText(tabelaOrcamento.getValueAt(tabelaOrcamento.getSelectedRow(), 0).toString());
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = ConexaoMySQL.getConexaoMySQL();
                java.sql.Statement st = conn.createStatement();
                st.executeQuery("SELECT * FROM `orcamentocontrole` WHERE `ID` = " + this.lID.getText());
                ResultSet rs = st.getResultSet();
                while (rs.next()) {
                    this.cBoxPlataforma.setSelectedItem(rs.getString("SEGMENTO"));
                    this.cBoxRegiao.setSelectedItem(rs.getString("REGIAO"));
                    this.cBoxFilial.setSelectedItem(rs.getString("DESCRICAO_FILIAL"));
                    this.cBoxMagnitude.setSelectedItem(rs.getString("MAGNITUDE_CONTA"));
                    this.cBoxCentroCusto.addItem(rs.getString("CENTRO_DE_CUSTO"));
                    this.cBoxCentroCusto.setSelectedItem(rs.getString("CENTRO_DE_CUSTO"));
                    this.cBoxConta.addItem(rs.getString("CONTA"));
                    this.cBoxConta.setSelectedItem(rs.getString("CONTA"));
                    this.cBoxNomeUsuario.setSelectedItem(rs.getString("RESPONSAVEL"));
                }
                this.jTextArea1.setText("INSERIR ANÁLISE");
                filtrarAnalise();
                ConexaoMySQL.FecharConexao();
            } catch (SQLException | ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, e);
                ConexaoMySQL.FecharConexao();
            }
        }
    }//GEN-LAST:event_tabelaOrcamentoMouseClicked

    private void cBoxMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxMesActionPerformed
        filtrar();
        filtrarAnalise();
    }//GEN-LAST:event_cBoxMesActionPerformed

    private void cBoxTipoOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxTipoOrcamentoActionPerformed
        filtrar();
    }//GEN-LAST:event_cBoxTipoOrcamentoActionPerformed

    private void bFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFiltrarActionPerformed
        filtrar();
        filtrarAnalise();
    }//GEN-LAST:event_bFiltrarActionPerformed

    private void cBoxFilialPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cBoxFilialPopupMenuWillBecomeVisible
        carregarFilial();
    }//GEN-LAST:event_cBoxFilialPopupMenuWillBecomeVisible

    private void cBoxRegiaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxRegiaoActionPerformed
        this.cBoxFilial.setSelectedItem("");
    }//GEN-LAST:event_cBoxRegiaoActionPerformed

    private void cBoxFilialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxFilialActionPerformed
        this.cBoxMagnitude.setSelectedItem("");
    }//GEN-LAST:event_cBoxFilialActionPerformed

    private void cBoxMagnitudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxMagnitudeActionPerformed
        this.cBoxCentroCusto.setSelectedItem("");
    }//GEN-LAST:event_cBoxMagnitudeActionPerformed

    private void cBoxCentroCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxCentroCustoActionPerformed
        this.cBoxConta.setSelectedItem("");
    }//GEN-LAST:event_cBoxCentroCustoActionPerformed

    private void cBoxMagnitudePopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cBoxMagnitudePopupMenuWillBecomeVisible
        carregarMagnitude();
    }//GEN-LAST:event_cBoxMagnitudePopupMenuWillBecomeVisible

    private void cBoxCentroCustoPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cBoxCentroCustoPopupMenuWillBecomeVisible
        carregarCentroCusto();
    }//GEN-LAST:event_cBoxCentroCustoPopupMenuWillBecomeVisible

    private void cBoxContaPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cBoxContaPopupMenuWillBecomeVisible
        carregarContaC();
    }//GEN-LAST:event_cBoxContaPopupMenuWillBecomeVisible

    private void bInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInserirActionPerformed
        Analise analise = new Analise();
        AnaliseSalvar salvaranalise = new AnaliseSalvar();
        Date dataatual = new Date();
        SimpleDateFormat forma = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String datas = forma.format(dataatual);

        String realizadomes;
        realizadomes = ((String) this.lRealMes.getText());
        realizadomes = realizadomes.replace(".", "");
        realizadomes = realizadomes.replace(",", ".");

        String realizadoacumulado;
        realizadoacumulado = ((String) this.lRealAcum.getText());
        realizadoacumulado = realizadoacumulado.replace(".", "");
        realizadoacumulado = realizadoacumulado.replace(",", ".");

        String orcamentomes;
        orcamentomes = ((String) this.lOrcadoMes.getText());
        orcamentomes = orcamentomes.replace(".", "");
        orcamentomes = orcamentomes.replace(",", ".");

        String orcamentoacumulado;
        orcamentoacumulado = ((String) this.lOrcadoAcum.getText());
        orcamentoacumulado = orcamentoacumulado.replace(".", "");
        orcamentoacumulado = orcamentoacumulado.replace(",", ".");

        analise.setMagnitude((String) cBoxMagnitude.getSelectedItem());
        analise.setRegiao((String) cBoxRegiao.getSelectedItem());
        analise.setFilial((String) cBoxFilial.getSelectedItem());
        analise.setConta((String) cBoxConta.getSelectedItem());
        analise.setCentrocusto((String) cBoxCentroCusto.getSelectedItem());
        analise.setPlataforma((String) cBoxPlataforma.getSelectedItem());
        analise.setBorr((String) cBoxTipoOrcamento.getSelectedItem());
        analise.setMes((String) cBoxMes.getSelectedItem());
        analise.setAnalise(jTextArea1.getText());
        analise.setRealmes(Double.parseDouble(realizadomes));
        analise.setRealacum(Double.parseDouble(realizadoacumulado));
        analise.setBdgmes(Double.parseDouble(orcamentomes));
        analise.setBdgacum(Double.parseDouble(orcamentoacumulado));
        analise.setUser(UsuarioLogado.usuario);
        analise.setDatareg(datas);
        analise.setTipoanalise((String) cBoxPreJustificativa.getSelectedItem());
        analise.setResponsavel((String) cBoxNomeUsuario.getSelectedItem());
        analise.setArea((String) cBoxArea.getSelectedItem());

        if (this.cBoxNomeUsuario.getSelectedItem() != "") {
            analise.setSituacao("PENDENTE");
        } else {
            analise.setSituacao("ANALISADO");
        }
        if (analise.getTipoanalise() == null) {
            analise.setTipoanalise("");
        }
        if (analise.getResponsavel() == null) {
            analise.setResponsavel("");
        }

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = ConexaoMySQL.getConexaoMySQL();
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("SELECT * FROM `orcamentocontrole` WHERE `CONTA` LIKE '%"
                    + this.cBoxConta.getSelectedItem() + "'");
            ResultSet rs = st.getResultSet();
            while (rs.next()) {
                analise.setDescconta(rs.getString("DESCRICAO_CONTA"));
            }
            st.executeQuery("SELECT * FROM `orcamentocontrole` WHERE `CENTRO_DE_CUSTO` LIKE '%"
                    + this.cBoxCentroCusto.getSelectedItem() + "'");
            ResultSet rss = st.getResultSet();
            while (rss.next()) {
                analise.setDesccentrocusto(rss.getString("DESCRICAO_CC"));
            }
            ConexaoMySQL.FecharConexao();
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(rootPane, e);
            ConexaoMySQL.FecharConexao();
        }

        salvaranalise.AnaliseSalvar(analise);
        filtrarAnalise();
        JOptionPane.showMessageDialog(this, "Análise incluida com sucesso");
    }//GEN-LAST:event_bInserirActionPerformed

    private void listAnalisesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listAnalisesMouseClicked
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = ConexaoMySQL.getConexaoMySQL();
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("SELECT * FROM `analiseorcamento` WHERE `ID` = '"
                    + this.listAnalises.getSelectedValue() + "'");
            ResultSet rs = st.getResultSet();
            while (rs.next()) {
                jTextArea1.setText(rs.getString("ANALISE"));
                lAnalisePlataforma.setText(rs.getString("PLATAFORMA"));
                lAnaliseRegiao.setText(rs.getString("REGIAO"));
                lAnaliseFilial.setText(rs.getString("DESCRICAO_FILIAL"));
                lAnaliseMagnitude.setText(rs.getString("MAGNITUDE_CONTA"));
                lAnaliseCentro.setText(rs.getString("DESCRICAO_CC"));
                lAnaliseConta.setText(rs.getString("DESCRICAO_CONTA"));
            }
            ConexaoMySQL.FecharConexao();
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(rootPane, e);
            ConexaoMySQL.FecharConexao();
        }
    }//GEN-LAST:event_listAnalisesMouseClicked

    private void cBoxNomeUsuarioPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cBoxNomeUsuarioPopupMenuWillBecomeVisible
        this.cBoxNomeUsuario.removeAllItems();
        this.cBoxNomeUsuario.addItem("");
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = ConexaoMySQL.getConexaoMySQL();
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("SELECT DISTINCT NOME FROM `usuario` WHERE `REGIAO` LIKE '%"
                    + this.cBoxRegiao.getSelectedItem() + "' AND `FILIAL` LIKE '%"
                    + this.cBoxFilial.getSelectedItem() + "' ORDER BY NOME");
            ResultSet rs = st.getResultSet();
            while (rs.next()) {
                cBoxNomeUsuario.addItem(rs.getString("NOME"));
            }
            ConexaoMySQL.FecharConexao();
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(rootPane, e);
            ConexaoMySQL.FecharConexao();
        }
    }//GEN-LAST:event_cBoxNomeUsuarioPopupMenuWillBecomeVisible

    private void cBoxPreJustificativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxPreJustificativaActionPerformed
        filtrarAnalise();
    }//GEN-LAST:event_cBoxPreJustificativaActionPerformed

    /**
     * @param args the command line arguments
     */
    public void carregarRegiao() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = ConexaoMySQL.getConexaoMySQL();
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("SELECT DISTINCT REGIAO FROM `orcamentocontrole` WHERE `SEGMENTO` LIKE '%"
                    + this.cBoxPlataforma.getSelectedItem() + "' ORDER BY REGIAO");
            ResultSet rs = st.getResultSet();
            while (rs.next()) {
                cBoxRegiao.addItem(rs.getString("REGIAO"));
            }
            ConexaoMySQL.FecharConexao();
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(rootPane, e);
            ConexaoMySQL.FecharConexao();
        }
    }

    public void carregarFilial() {
        this.cBoxFilial.removeAllItems();
        this.cBoxFilial.addItem("");
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = ConexaoMySQL.getConexaoMySQL();
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("SELECT DISTINCT DESCRICAO_FILIAL FROM `orcamentocontrole` WHERE `REGIAO` LIKE '%"
                    + this.cBoxRegiao.getSelectedItem() + "' AND `SEGMENTO` LIKE '%"
                    + this.cBoxPlataforma.getSelectedItem() + "' ORDER BY DESCRICAO_FILIAL");
            ResultSet rs = st.getResultSet();
            while (rs.next()) {
                cBoxFilial.addItem(rs.getString("DESCRICAO_FILIAL"));
            }
            ConexaoMySQL.FecharConexao();
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(rootPane, e);
            ConexaoMySQL.FecharConexao();
        }
    }

    public void carregarMagnitude() {
        this.cBoxMagnitude.removeAllItems();
        this.cBoxMagnitude.addItem("");
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = ConexaoMySQL.getConexaoMySQL();
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("SELECT DISTINCT MAGNITUDE_CONTA FROM `orcamentocontrole` WHERE `REGIAO` LIKE '%"
                    + this.cBoxRegiao.getSelectedItem() + "' AND `SEGMENTO` LIKE '%"
                    + this.cBoxPlataforma.getSelectedItem() + "' AND `DESCRICAO_FILIAL` LIKE '%"
                    + this.cBoxFilial.getSelectedItem() + "' ORDER BY MAGNITUDE_CONTA");
            ResultSet rs = st.getResultSet();
            while (rs.next()) {
                cBoxMagnitude.addItem(rs.getString("MAGNITUDE_CONTA"));
            }
            ConexaoMySQL.FecharConexao();
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(rootPane, e);
            ConexaoMySQL.FecharConexao();
        }
    }

    public void carregarCentroCusto() {
        this.cBoxCentroCusto.removeAllItems();
        this.cBoxCentroCusto.addItem("");
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = ConexaoMySQL.getConexaoMySQL();
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("SELECT DISTINCT CENTRO_DE_CUSTO FROM `orcamentocontrole` WHERE `REGIAO` LIKE '%"
                    + this.cBoxRegiao.getSelectedItem() + "' AND `SEGMENTO` LIKE '%"
                    + this.cBoxPlataforma.getSelectedItem() + "' AND `DESCRICAO_FILIAL` LIKE '%"
                    + this.cBoxFilial.getSelectedItem() + "' AND `MAGNITUDE_CONTA` LIKE '%"
                    + this.cBoxMagnitude.getSelectedItem() + "' ORDER BY CENTRO_DE_CUSTO");
            ResultSet rs = st.getResultSet();
            while (rs.next()) {
                cBoxCentroCusto.addItem(rs.getString("CENTRO_DE_CUSTO"));
            }
            ConexaoMySQL.FecharConexao();
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(rootPane, e);
            ConexaoMySQL.FecharConexao();
        }
    }

    public void carregarContaC() {
        this.cBoxConta.removeAllItems();
        this.cBoxConta.addItem("");
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = ConexaoMySQL.getConexaoMySQL();
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("SELECT DISTINCT CONTA FROM `orcamentocontrole` WHERE `REGIAO` LIKE '%"
                    + this.cBoxRegiao.getSelectedItem() + "' AND `SEGMENTO` LIKE '%"
                    + this.cBoxPlataforma.getSelectedItem() + "' AND `DESCRICAO_FILIAL` LIKE '%"
                    + this.cBoxFilial.getSelectedItem() + "' AND `MAGNITUDE_CONTA` LIKE '%"
                    + this.cBoxMagnitude.getSelectedItem() + "' AND `CENTRO_DE_CUSTO` LIKE '%"
                    + this.cBoxCentroCusto.getSelectedItem() + "' ORDER BY CONTA");
            ResultSet rs = st.getResultSet();
            while (rs.next()) {
                cBoxConta.addItem(rs.getString("CONTA"));
            }
            ConexaoMySQL.FecharConexao();
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(rootPane, e);
            ConexaoMySQL.FecharConexao();
        }
    }

    public void carregarArea() {
        this.cBoxArea.removeAllItems();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = ConexaoMySQL.getConexaoMySQL();
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("SELECT DISTINCT RESPONSAVEL FROM `orcamentocontrole` ORDER BY RESPONSAVEL");
            ResultSet rs = st.getResultSet();
            while (rs.next()) {
                cBoxArea.addItem(rs.getString("RESPONSAVEL"));
            }
            ConexaoMySQL.FecharConexao();
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(rootPane, e);
            ConexaoMySQL.FecharConexao();
        }
    }

    public void limparParte() {
        if (("Operacional").equals(UsuarioLogado.perfil)) {

        } else if (("Supervisor").equals(UsuarioLogado.perfil)) {
            this.cBoxFilial.setSelectedItem("");

        } else {
            this.cBoxRegiao.setSelectedItem("");
            this.cBoxFilial.setSelectedItem("");
        }
        this.cBoxNomeUsuario.setSelectedItem("");
        this.cBoxMagnitude.setSelectedItem("");
        this.cBoxCentroCusto.setSelectedItem("");
        this.cBoxConta.setSelectedItem("");
        this.lID.setText("");
        this.jTextArea1.setText("INSERIR ANÁLISE");
        this.cBoxPlataforma.setSelectedItem("");
        filtrar();
    }

    public void diferencaMes() {
        DecimalFormat df = new DecimalFormat("###,###,###,##0.00");
        df.setRoundingMode(RoundingMode.UP);
        int count = tabelaOrcamento.getRowCount();
        for (int row = count - 1; row >= 0; row--) {
            Double realmes = (Double) tabelaOrcamento.getValueAt(row, 10);
            Double bdgmes = (Double) tabelaOrcamento.getValueAt(row, 9);
            String dm = String.valueOf(df.format(bdgmes - realmes));
            dm = dm.replace(".", "");
            dm = dm.replace(",", ".");
            Double difmes = Double.parseDouble(dm);
            tabelaOrcamento.setValueAt(difmes, row, 11);

            Double realacum = (Double) tabelaOrcamento.getValueAt(row, 13);
            Double bdgacum = (Double) tabelaOrcamento.getValueAt(row, 12);
            String da = String.valueOf(df.format(bdgacum - realacum));
            da = da.replace(".", "");
            da = da.replace(",", ".");
            Double difacum = Double.parseDouble(da);
            tabelaOrcamento.setValueAt(difacum, row, 14);
        }
    }

    public void filtrar() {
        acumulado();
        String responsavel = "";
        String textselarea = "";
        if (this.cBoxArea.getSelectedItem() == null) {
            textselarea = "";
        } else {
            textselarea = (String) this.cBoxArea.getSelectedItem();
        }
        String areauserlog = UsuarioLogado.area;

        String area = "";
        if ("Operacional".equals(UsuarioLogado.perfil)) {
            if (!textselarea.equals(areauserlog)) {
                area = " AND `RESPONSAVEL` LIKE '%" + UsuarioLogado.area + "'";
            }
        }
        DecimalFormat df = new DecimalFormat("###,###,###,##0.00");
        df.setRoundingMode(RoundingMode.UP);
        DefaultTableModel modelo = (DefaultTableModel) tabelaOrcamento.getModel();
        tabelaOrcamento.setRowSorter(new TableRowSorter(modelo));
        modelo.setNumRows(0);
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = ConexaoMySQL.getConexaoMySQL();
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("SELECT REGIAO, ID, SEGMENTO, CENTRO_DE_CUSTO, DESCRICAO_CC, DESCRICAO_FILIAL, MAGNITUDE_CONTA, CONTA, DESCRICAO_CONTA, SEGMENTO, RESPONSAVEL,  SUM(REAL_JAN) AS REAL_JAN_GROUP, SUM(REAL_FEV) AS REAL_FEV_GROUP, SUM(REAL_MAR) AS REAL_MAR_GROUP, SUM(REAL_ABR) AS REAL_ABR_GROUP, SUM(REAL_MAI) AS REAL_MAI_GROUP, SUM(REAL_JUN) AS REAL_JUN_GROUP, SUM(REAL_JUL) AS REAL_JUL_GROUP, SUM(REAL_AGO) AS REAL_AGO_GROUP, SUM(REAL_SET) AS REAL_SET_GROUP, SUM(REAL_OUT) AS REAL_OUT_GROUP, SUM(REAL_NOV) AS REAL_NOV_GROUP, SUM(REAL_DEZ) AS REAL_DEZ_GROUP, SUM(REAL_ACUM) AS REAL_ACUM_GROUP, SUM(BDG_JAN) AS BDG_JAN_GROUP, SUM(BDG_FEV) AS BDG_FEV_GROUP, SUM(BDG_MAR) AS BDG_MAR_GROUP, SUM(BDG_ABR) AS BDG_ABR_GROUP, SUM(BDG_MAI) AS BDG_MAI_GROUP, SUM(BDG_JUN) AS BDG_JUN_GROUP, SUM(BDG_JUL) AS BDG_JUL_GROUP, SUM(BDG_AGO) AS BDG_AGO_GROUP, SUM(BDG_SET) AS BDG_SET_GROUP, SUM(BDG_OUT) AS BDG_OUT_GROUP, SUM(BDG_NOV) AS BDG_NOV_GROUP, SUM(BDG_DEZ) AS BDG_DEZ_GROUP, SUM(BDG_ACUM) AS BDG_ACUM_GROUP, SUM(RFC_JAN) AS RFC_JAN_GROUP, SUM(RFC_FEV) AS RFC_FEV_GROUP, SUM(RFC_MAR) AS RFC_MAR_GROUP, SUM(RFC_ABR) AS RFC_ABR_GROUP, SUM(RFC_MAI) AS RFC_MAI_GROUP, SUM(RFC_JUN) AS RFC_JUN_GROUP, SUM(RFC_JUL) AS RFC_JUL_GROUP, SUM(RFC_AGO) AS RFC_AGO_GROUP, SUM(RFC_SET) AS RFC_SET_GROUP, SUM(RFC_OUT) AS RFC_OUT_GROUP, SUM(RFC_NOV) AS RFC_NOV_GROUP, SUM(RFC_DEZ) AS RFC_DEZ_GROUP, SUM(RFC_ACUM) AS RFC_ACUM_GROUP, SUM(BDG_ANUAL) AS BDG_ANUAL_GROUP, SUM(RFC_ANUAL) AS RFC_ANUAL_GROUP FROM `orcamentocontrole` WHERE `REGIAO` LIKE '%"
                    + this.cBoxRegiao.getSelectedItem() + "' AND `DESCRICAO_FILIAL` LIKE '%"
                    + this.cBoxFilial.getSelectedItem() + "' AND `MAGNITUDE_CONTA` LIKE '%"
                    + this.cBoxMagnitude.getSelectedItem() + "' AND `CENTRO_DE_CUSTO` LIKE '%"
                    + this.cBoxCentroCusto.getSelectedItem() + "' AND `CONTA` LIKE '%"
                    + this.cBoxConta.getSelectedItem() + "' AND `SEGMENTO` LIKE '%"
                    + this.cBoxPlataforma.getSelectedItem() + "' AND `RESPONSAVEL` LIKE '%"
                    + this.cBoxArea.getSelectedItem() + "' " + area
                    + "GROUP BY REGIAO, SEGMENTO, CENTRO_DE_CUSTO, DESCRICAO_FILIAL, MAGNITUDE_CONTA, CONTA, SEGMENTO;");
            ResultSet rs = st.getResultSet();

            while (rs.next()) {
                Double bdgmes = rs.getDouble(this.cBoxTipoOrcamento.getSelectedItem() + "_" + this.cBoxMes.getSelectedItem() + "_GROUP");
                String bm = String.valueOf(df.format(bdgmes));
                bm = bm.replace(".", "");
                bm = bm.replace(",", ".");
                bdgmes = Double.parseDouble(bm);

                Double realmes = rs.getDouble("REAL_" + this.cBoxMes.getSelectedItem() + "_GROUP");
                String rm = String.valueOf(df.format(realmes));
                rm = rm.replace(".", "");
                rm = rm.replace(",", ".");
                realmes = Double.parseDouble(rm);

                Double bdgacum = rs.getDouble(this.cBoxTipoOrcamento.getSelectedItem() + "_ACUM_GROUP");
                String ba = String.valueOf(df.format(bdgacum));
                ba = ba.replace(".", "");
                ba = ba.replace(",", ".");
                bdgacum = Double.parseDouble(ba);

                Double realacum = rs.getDouble("REAL_ACUM_GROUP");
                String ra = String.valueOf(df.format(realacum));
                ra = ra.replace(".", "");
                ra = ra.replace(",", ".");
                realacum = Double.parseDouble(ra);

                modelo.addRow(new Object[]{
                    rs.getInt("ID"),
                    rs.getString("SEGMENTO"),
                    rs.getObject("REGIAO"),
                    rs.getString("CENTRO_DE_CUSTO"),
                    rs.getString("DESCRICAO_CC"),
                    rs.getString("DESCRICAO_FILIAL"),
                    rs.getString("MAGNITUDE_CONTA"),
                    rs.getString("CONTA"),
                    rs.getString("DESCRICAO_CONTA"),
                    bdgmes,
                    realmes,
                    rs.getDouble(2),
                    bdgacum,
                    realacum,
                    rs.getDouble(2),});
            }

            if ("Operacional".equals(UsuarioLogado.perfil)) {
                if (!textselarea.equals(areauserlog)) {
                    st.executeQuery("SELECT REGIAO, ID, SEGMENTO, CENTRO_DE_CUSTO, DESCRICAO_CC, DESCRICAO_FILIAL, MAGNITUDE_CONTA, CONTA, DESCRICAO_CONTA, SEGMENTO, RESPONSAVEL,  SUM(REAL_JAN) AS REAL_JAN_GROUP, SUM(REAL_FEV) AS REAL_FEV_GROUP, SUM(REAL_MAR) AS REAL_MAR_GROUP, SUM(REAL_ABR) AS REAL_ABR_GROUP, SUM(REAL_MAI) AS REAL_MAI_GROUP, SUM(REAL_JUN) AS REAL_JUN_GROUP, SUM(REAL_JUL) AS REAL_JUL_GROUP, SUM(REAL_AGO) AS REAL_AGO_GROUP, SUM(REAL_SET) AS REAL_SET_GROUP, SUM(REAL_OUT) AS REAL_OUT_GROUP, SUM(REAL_NOV) AS REAL_NOV_GROUP, SUM(REAL_DEZ) AS REAL_DEZ_GROUP, SUM(REAL_ACUM) AS REAL_ACUM_GROUP, SUM(BDG_JAN) AS BDG_JAN_GROUP, SUM(BDG_FEV) AS BDG_FEV_GROUP, SUM(BDG_MAR) AS BDG_MAR_GROUP, SUM(BDG_ABR) AS BDG_ABR_GROUP, SUM(BDG_MAI) AS BDG_MAI_GROUP, SUM(BDG_JUN) AS BDG_JUN_GROUP, SUM(BDG_JUL) AS BDG_JUL_GROUP, SUM(BDG_AGO) AS BDG_AGO_GROUP, SUM(BDG_SET) AS BDG_SET_GROUP, SUM(BDG_OUT) AS BDG_OUT_GROUP, SUM(BDG_NOV) AS BDG_NOV_GROUP, SUM(BDG_DEZ) AS BDG_DEZ_GROUP, SUM(BDG_ACUM) AS BDG_ACUM_GROUP, SUM(RFC_JAN) AS RFC_JAN_GROUP, SUM(RFC_FEV) AS RFC_FEV_GROUP, SUM(RFC_MAR) AS RFC_MAR_GROUP, SUM(RFC_ABR) AS RFC_ABR_GROUP, SUM(RFC_MAI) AS RFC_MAI_GROUP, SUM(RFC_JUN) AS RFC_JUN_GROUP, SUM(RFC_JUL) AS RFC_JUL_GROUP, SUM(RFC_AGO) AS RFC_AGO_GROUP, SUM(RFC_SET) AS RFC_SET_GROUP, SUM(RFC_OUT) AS RFC_OUT_GROUP, SUM(RFC_NOV) AS RFC_NOV_GROUP, SUM(RFC_DEZ) AS RFC_DEZ_GROUP, SUM(RFC_ACUM) AS RFC_ACUM_GROUP, SUM(BDG_ANUAL) AS BDG_ANUAL_GROUP, SUM(RFC_ANUAL) AS RFC_ANUAL_GROUP FROM `orcamentocontrole` WHERE `REGIAO` LIKE '%"
                            + this.cBoxRegiao.getSelectedItem() + "' AND `DESCRICAO_FILIAL` LIKE '%"
                            + this.cBoxFilial.getSelectedItem() + "' AND `MAGNITUDE_CONTA` LIKE '%"
                            + this.cBoxMagnitude.getSelectedItem() + "' AND `MAGNITUDE_CONTA` "
                            + "NOT LIKE 'Employment Cost' AND `CENTRO_DE_CUSTO` LIKE '%"
                            + this.cBoxCentroCusto.getSelectedItem() + "' AND `CONTA` LIKE '%"
                            + this.cBoxConta.getSelectedItem() + "' AND `SEGMENTO` LIKE '%"
                            + this.cBoxPlataforma.getSelectedItem() + "' AND `RESPONSAVEL` LIKE '%"
                            + this.cBoxArea.getSelectedItem() + "' AND `RESPONSAVEL` NOT LIKE '"
                            + UsuarioLogado.area + "' GROUP BY REGIAO, SEGMENTO, CENTRO_DE_CUSTO, DESCRICAO_FILIAL, MAGNITUDE_CONTA, CONTA, SEGMENTO;");
                    ResultSet rss = st.getResultSet();

                    while (rss.next()) {
                        Double bdgmes = rss.getDouble(this.cBoxTipoOrcamento.getSelectedItem() + "_" + this.cBoxMes.getSelectedItem() + "_GROUP");
                        String bm = String.valueOf(df.format(bdgmes));
                        bm = bm.replace(".", "");
                        bm = bm.replace(",", ".");
                        bdgmes = Double.parseDouble(bm);

                        Double realmes = rss.getDouble("REAL_" + this.cBoxMes.getSelectedItem() + "_GROUP");
                        String rm = String.valueOf(df.format(realmes));
                        rm = rm.replace(".", "");
                        rm = rm.replace(",", ".");
                        realmes = Double.parseDouble(rm);

                        Double bdgacum = rss.getDouble(this.cBoxTipoOrcamento.getSelectedItem() + "_ACUM_GROUP");
                        String ba = String.valueOf(df.format(bdgacum));
                        ba = ba.replace(".", "");
                        ba = ba.replace(",", ".");
                        bdgacum = Double.parseDouble(ba);

                        Double realacum = rss.getDouble("REAL_ACUM_GROUP");
                        String ra = String.valueOf(df.format(realacum));
                        ra = ra.replace(".", "");
                        ra = ra.replace(",", ".");
                        realacum = Double.parseDouble(ra);

                        modelo.addRow(new Object[]{
                            rss.getInt("ID"),
                            rss.getString("SEGMENTO"),
                            rss.getObject("REGIAO"),
                            rss.getString("CENTRO_DE_CUSTO"),
                            rss.getString("DESCRICAO_CC"),
                            rss.getString("DESCRICAO_FILIAL"),
                            rss.getString("MAGNITUDE_CONTA"),
                            rss.getString("CONTA"),
                            rss.getString("DESCRICAO_CONTA"),
                            bdgmes,
                            realmes,
                            rss.getDouble(2),
                            bdgacum,
                            realacum,
                            rss.getDouble(2),});
                    }
                }
            }

            ConexaoMySQL.FecharConexao();
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(rootPane, e);
            ConexaoMySQL.FecharConexao();
        }
        diferencaMes();
        somarValoresdaTabela();
        corNaLinha();

    }

    public void filtrarAnalise() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = ConexaoMySQL.getConexaoMySQL();
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("SELECT * FROM `analiseorcamento` WHERE `REGIAO` LIKE '%"
                    + this.cBoxRegiao.getSelectedItem() + "' AND `DESCRICAO_FILIAL` LIKE '%"
                    + this.cBoxFilial.getSelectedItem() + "' AND `MAGNITUDE_CONTA` LIKE '%"
                    + this.cBoxMagnitude.getSelectedItem() + "' AND `CENTRO_DE_CUSTO` LIKE '%"
                    + this.cBoxCentroCusto.getSelectedItem() + "' AND `CONTA` LIKE '%"
                    + this.cBoxConta.getSelectedItem() + "' AND `PLATAFORMA` LIKE '%"
                    + this.cBoxPlataforma.getSelectedItem() + "' AND `MES` LIKE '%"
                    + this.cBoxMes.getSelectedItem() + "' AND `BORR` LIKE '%"
                    + this.cBoxTipoOrcamento.getSelectedItem() + "' AND `TIPOJUS` LIKE '%"
                    + this.cBoxPreJustificativa.getSelectedItem() + "';");

            ResultSet rss = st.getResultSet();
            List analises = new ArrayList();

            if (rss.first()) {
                int teste = 1;
                analises.add(rss.getString("ID"));
                while (rss.next()) {
                    analises.add(rss.getString("ID"));
                    teste++;
                }
                this.listAnalises.setListData(analises.toArray());
                this.lNumeroAnalises.setText(String.valueOf(teste));
            } else {
                this.listAnalises.setListData(analises.toArray());
                this.lNumeroAnalises.setText(String.valueOf(0));
            }

            ConexaoMySQL.FecharConexao();
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(rootPane, e);
            ConexaoMySQL.FecharConexao();
        }
        diferencaMes();
        somarValoresdaTabela();
    }

    public void selmes() {
        DataHoje dh = new DataHoje();
        dh.Data();
        this.cBoxMes.setSelectedItem(dh.getDatahoje());
    }

    public void somarValoresdaTabela() {
        DecimalFormat df = new DecimalFormat("###,###,###,###.##");
        df.setRoundingMode(RoundingMode.UP);

        double realmes = 0;
        double realacum = 0;
        double bgdmes = 0;
        double bdgacum = 0;
        double difmes = 0;
        double difacum = 0;
        for (int i = 0; i <= tabelaOrcamento.getRowCount() - 1; i++) {
            realmes += Double.parseDouble(tabelaOrcamento.getValueAt(i, 10).toString());
            realacum += Double.parseDouble(tabelaOrcamento.getValueAt(i, 13).toString());
            bgdmes += Double.parseDouble(tabelaOrcamento.getValueAt(i, 9).toString());
            bdgacum += Double.parseDouble(tabelaOrcamento.getValueAt(i, 12).toString());
            difmes += Double.parseDouble(tabelaOrcamento.getValueAt(i, 11).toString());
            difacum += Double.parseDouble(tabelaOrcamento.getValueAt(i, 14).toString());
        }
        lOrcadoMes.setText(String.valueOf(df.format(bgdmes)));
        lOrcadoAcum.setText(String.valueOf(df.format(bdgacum)));
        lRealMes.setText(String.valueOf(df.format(realmes)));
        lRealAcum.setText(String.valueOf(df.format(realacum)));
        lDiferencaMes.setText(String.valueOf(df.format(difmes)));
        lDiferencaAcum.setText(String.valueOf(df.format(difacum)));
    }

    public void acumulado() {
        try {
            RealAcum rac = new RealAcum();
            rac.buscaMes();
            BdgAcum bac = new BdgAcum();
            bac.setMesselecionado((String) this.cBoxTipoOrcamento.getSelectedItem());
            bac.buscaMes();

            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = ConexaoMySQL.getConexaoMySQL();
            java.sql.Statement st = conn.createStatement();
            if (this.cBoxMes.getSelectedItem() == "JAN") {
                st.executeUpdate(rac.getJaneiro());
                st.executeUpdate(bac.getJaneiro());
            } else if (this.cBoxMes.getSelectedItem() == "FEV") {
                st.executeUpdate(rac.getFevereiro());
                st.executeUpdate(bac.getFevereiro());
            } else if (this.cBoxMes.getSelectedItem() == "MAR") {
                st.executeUpdate(rac.getMarco());
                st.executeUpdate(bac.getMarco());
            } else if (this.cBoxMes.getSelectedItem() == "ABR") {
                st.executeUpdate(rac.getAbril());
                st.executeUpdate(bac.getAbril());
            } else if (this.cBoxMes.getSelectedItem() == "MAI") {
                st.executeUpdate(rac.getMaio());
                st.executeUpdate(bac.getMaio());
            } else if (this.cBoxMes.getSelectedItem() == "JUN") {
                st.executeUpdate(rac.getJunho());
                st.executeUpdate(bac.getJunho());
            } else if (this.cBoxMes.getSelectedItem() == "JUL") {
                st.executeUpdate(rac.getJulho());
                st.executeUpdate(bac.getJulho());
            } else if (this.cBoxMes.getSelectedItem() == "AGO") {
                st.executeUpdate(rac.getAgosto());
                st.executeUpdate(bac.getAgosto());
            } else if (this.cBoxMes.getSelectedItem() == "SET") {
                st.executeUpdate(rac.getSetembro());
                st.executeUpdate(bac.getSetembro());
            } else if (this.cBoxMes.getSelectedItem() == "OUT") {
                st.executeUpdate(rac.getOutubro());
                st.executeUpdate(bac.getOutubro());
            } else if (this.cBoxMes.getSelectedItem() == "NOV") {
                st.executeUpdate(rac.getNovembro());
                st.executeUpdate(bac.getNovembro());
            } else if (this.cBoxMes.getSelectedItem() == "DEZ") {
                st.executeUpdate(rac.getDezembro());
                st.executeUpdate(bac.getDezembro());
            }
            ConexaoMySQL.FecharConexao();
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(rootPane, e);
            ConexaoMySQL.FecharConexao();
        }
    }

    public void acesso() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = ConexaoMySQL.getConexaoMySQL();
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("SELECT * FROM `usuario` WHERE `USUARIO` LIKE '" + UsuarioLogado.usuario + "';");
            ResultSet rss = st.getResultSet();
            if (rss.first()) {
                if ("Operacional".equals(rss.getString("PERFIL"))) {
                    this.cBoxRegiao.setSelectedItem((String) rss.getString("REGIAO"));
                    this.cBoxFilial.setSelectedItem((String) rss.getString("FILIAL"));
                    this.cBoxRegiao.setEnabled(false);
                    this.cBoxFilial.setEnabled(false);
                    this.jPanel1.setVisible(false);
                } else if ("Administrador".equals(rss.getString("PERFIL"))) {

                } else if ("Supervisor".equals(rss.getString("PERFIL"))) {
                    this.cBoxRegiao.setSelectedItem((String) rss.getString("REGIAO"));
                    this.cBoxRegiao.setEnabled(false);
                } else if ("Observador".equals(rss.getString("PERFIL"))) {
                }
            } else {
                dispose();
            }
            ConexaoMySQL.FecharConexao();
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(rootPane, e);
            ConexaoMySQL.FecharConexao();
        }
    }

    public void corNaLinha() {

        tabelaOrcamento.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {
                Component cell = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                Color corDiferencaMes = new java.awt.Color(255, 182, 193);
                if (column == 11 || column == 14) {
                    Double var = (Double) value;
                    if (var < 0) {
                        cell.setBackground(corDiferencaMes);
                    }
                } else {
                    cell.setBackground(Color.WHITE);
                }
                return cell;
            }
        });
    }

    public void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/br/com/controleorcamento/imagens/LDC_logo.png")));
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaliseOrcamento.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaliseOrcamento.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaliseOrcamento.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaliseOrcamento.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaliseOrcamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bFiltrar;
    private javax.swing.JButton bInserir;
    private javax.swing.JButton bLimpar;
    private javax.swing.JComboBox<Object> cBoxArea;
    private javax.swing.JComboBox<Object> cBoxCentroCusto;
    private javax.swing.JComboBox<Object> cBoxConta;
    private javax.swing.JComboBox<String> cBoxFilial;
    private javax.swing.JComboBox<Object> cBoxMagnitude;
    private javax.swing.JComboBox<String> cBoxMes;
    private javax.swing.JComboBox<Object> cBoxNomeUsuario;
    private javax.swing.JComboBox<String> cBoxPlataforma;
    private javax.swing.JComboBox<Object> cBoxPreJustificativa;
    private javax.swing.JComboBox<String> cBoxRegiao;
    private javax.swing.JComboBox<String> cBoxTipoOrcamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lAnaliseCentro;
    private javax.swing.JLabel lAnaliseConta;
    private javax.swing.JLabel lAnaliseFilial;
    private javax.swing.JLabel lAnaliseMagnitude;
    private javax.swing.JLabel lAnalisePlataforma;
    private javax.swing.JLabel lAnaliseRegiao;
    private javax.swing.JLabel lDiferencaAcum;
    private javax.swing.JLabel lDiferencaMes;
    private javax.swing.JLabel lID;
    private javax.swing.JLabel lNumeroAnalises;
    private javax.swing.JLabel lOrcadoAcum;
    private javax.swing.JLabel lOrcadoMes;
    private javax.swing.JLabel lRealAcum;
    private javax.swing.JLabel lRealMes;
    private javax.swing.JList<Object> listAnalises;
    private javax.swing.JTable tabelaOrcamento;
    // End of variables declaration//GEN-END:variables

    private String getValueAt(String rmes) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
