/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.controleorcamento.formularios;

import br.com.controleorcamento.atividades.ConexaoMySQL;
import br.com.controleorcamento.objeto.DataHoje;
import br.com.controleorcamento.objeto.UsuarioLogado;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author rosaan
 */
public class AnaliseConsulta extends javax.swing.JFrame {

    /**
     * Creates new form AnaliseOrcamento
     */
    public AnaliseConsulta() {
        initComponents();
        selmes();
        carregarRegiao();
        carregarFilial();
        carregarMagnitude();
        carregarCentroCusto();
        carregarContaC();
        limparParte();
        acesso();
        filtrarAnalise();
        setIcon();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cBoxMagnitude = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cBoxRegiao = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cBoxFilial = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cBoxCentroCusto = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cBoxConta = new javax.swing.JComboBox<>();
        bLimpar = new javax.swing.JButton();
        lID = new javax.swing.JLabel();
        cBoxMes = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cBoxTipoOrcamento = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        lCentroCusto1 = new javax.swing.JLabel();
        lCentroCusto2 = new javax.swing.JLabel();
        bFiltrar = new javax.swing.JButton();
        cBoxPlataforma = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listAnalises = new javax.swing.JList<>();
        lNumeroAnalises = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cBoxPreJustificativa = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lOrcadoMes = new javax.swing.JLabel();
        lRealMes = new javax.swing.JLabel();
        lDiferencaMes = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lOrcadoAcum = new javax.swing.JLabel();
        lRealAcum = new javax.swing.JLabel();
        lDiferencaAcum = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        lAnaliseConta = new javax.swing.JLabel();
        lAnaliseCentro = new javax.swing.JLabel();
        lAnaliseMagnitude = new javax.swing.JLabel();
        lAnaliseFilial = new javax.swing.JLabel();
        lAnaliseRegiao = new javax.swing.JLabel();
        lAnalisePlataforma = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/controleorcamento/imagens/icons8-Pesquisar-16.png"))); // NOI18N
        jLabel1.setText("Consulta Orçamento");

        jLabel2.setText("Magnitude");

        cBoxMagnitude.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cBoxMagnitudePopupMenuWillBecomeVisible(evt);
            }
        });
        cBoxMagnitude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxMagnitudeActionPerformed(evt);
            }
        });

        jLabel3.setText("Região");

        cBoxRegiao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxRegiaoActionPerformed(evt);
            }
        });

        jLabel4.setText("Filial");

        cBoxFilial.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cBoxFilialPopupMenuWillBecomeVisible(evt);
            }
        });
        cBoxFilial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxFilialActionPerformed(evt);
            }
        });

        jLabel5.setText("Centro de Custo");

        cBoxCentroCusto.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cBoxCentroCustoPopupMenuWillBecomeVisible(evt);
            }
        });
        cBoxCentroCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxCentroCustoActionPerformed(evt);
            }
        });

        jLabel6.setText("Conta");

        cBoxConta.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cBoxContaPopupMenuWillBecomeVisible(evt);
            }
        });

        bLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/controleorcamento/imagens/icons8-Vassoura-16.png"))); // NOI18N
        bLimpar.setText("Limpar");
        bLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimparActionPerformed(evt);
            }
        });

        cBoxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JAN", "FEV", "MAR", "ABR", "MAI", "JUN", "JUL", "AGO", "SET", "OUT", "NOV", "DEZ" }));
        cBoxMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxMesActionPerformed(evt);
            }
        });

        jLabel7.setText("Mês");

        jLabel8.setText("Orçamento");

        cBoxTipoOrcamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BDG", "RFC" }));

        bFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/controleorcamento/imagens/icons8-Filtro-16.png"))); // NOI18N
        bFiltrar.setText("Filtrar");
        bFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFiltrarActionPerformed(evt);
            }
        });

        cBoxPlataforma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "MILHO", "SOJA" }));

        jLabel10.setText("Plataforma");

        listAnalises.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listAnalisesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listAnalises);

        lNumeroAnalises.setText("0");

        jLabel16.setText("Análises Cadastradas:");

        cBoxPreJustificativa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Bonus", "Cancelamentos Extemporâneos", "Dentro do Orçamento Anual", "Desligamento de Profissional", "Encargos", "Horas Extras", "Multa", "Orçamento Subestimado", "Orçamento Superestimado", "Reclassificação", "Sem Orçamento", "Viagem", "" }));

        jLabel17.setText("Tipo de Justificativa");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel15.setText("Informações");

        jLabel14.setText("Valor Orçado");

        jLabel11.setText("Valor Real");

        jLabel20.setText("Diferença");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Mês");

        lOrcadoMes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lOrcadoMes.setText("Valor Orçado");

        lRealMes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lRealMes.setText("Valor Real");

        lDiferencaMes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lDiferencaMes.setText("Diferença");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Acumulado");

        lOrcadoAcum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lOrcadoAcum.setText("Valor Orçado");

        lRealAcum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lRealAcum.setText("Valor Real");

        lDiferencaAcum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lDiferencaAcum.setText("Diferença");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lRealMes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lOrcadoMes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lDiferencaMes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lRealAcum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lOrcadoAcum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lDiferencaAcum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lOrcadoMes)
                    .addComponent(lOrcadoAcum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lRealMes)
                    .addComponent(lRealAcum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(lDiferencaMes)
                    .addComponent(lDiferencaAcum))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lOrcadoMes.getAccessibleContext().setAccessibleDescription("");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lAnaliseConta.setText("-");

        lAnaliseCentro.setText("-");

        lAnaliseMagnitude.setText("-");

        lAnaliseFilial.setText("-");

        lAnaliseRegiao.setText("-");

        lAnalisePlataforma.setText("-");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lAnalisePlataforma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lAnaliseRegiao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lAnaliseFilial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lAnaliseMagnitude, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lAnaliseCentro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lAnaliseConta, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lAnalisePlataforma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lAnaliseRegiao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lAnaliseFilial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lAnaliseMagnitude)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lAnaliseCentro)
                .addGap(8, 8, 8)
                .addComponent(lAnaliseConta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(cBoxTipoOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(cBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lID)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cBoxRegiao, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cBoxMagnitude, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cBoxFilial, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cBoxConta, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cBoxCentroCusto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cBoxPlataforma, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bLimpar))
                                    .addComponent(cBoxPreJustificativa, 0, 195, Short.MAX_VALUE))))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lNumeroAnalises, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(349, 349, 349)
                                .addComponent(lCentroCusto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lCentroCusto2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(lID))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cBoxTipoOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cBoxPlataforma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cBoxRegiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cBoxFilial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cBoxMagnitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cBoxCentroCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cBoxConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cBoxPreJustificativa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(5, 5, 5)
                                .addComponent(lNumeroAnalises))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(lCentroCusto1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(lCentroCusto2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bFiltrar)
                        .addComponent(bLimpar))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimparActionPerformed
        limparParte();
    }//GEN-LAST:event_bLimparActionPerformed

    private void cBoxMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxMesActionPerformed
        filtrarAnalise();
    }//GEN-LAST:event_cBoxMesActionPerformed

    private void bFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFiltrarActionPerformed
        filtrarAnalise();
    }//GEN-LAST:event_bFiltrarActionPerformed

    private void cBoxFilialPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cBoxFilialPopupMenuWillBecomeVisible
        carregarFilial();
    }//GEN-LAST:event_cBoxFilialPopupMenuWillBecomeVisible

    private void cBoxRegiaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxRegiaoActionPerformed
        this.cBoxFilial.setSelectedItem("");
    }//GEN-LAST:event_cBoxRegiaoActionPerformed

    private void cBoxFilialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxFilialActionPerformed
        this.cBoxMagnitude.setSelectedItem("");
    }//GEN-LAST:event_cBoxFilialActionPerformed

    private void cBoxMagnitudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxMagnitudeActionPerformed
        this.cBoxCentroCusto.setSelectedItem("");
    }//GEN-LAST:event_cBoxMagnitudeActionPerformed

    private void cBoxCentroCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxCentroCustoActionPerformed
        this.cBoxConta.setSelectedItem("");
    }//GEN-LAST:event_cBoxCentroCustoActionPerformed

    private void cBoxMagnitudePopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cBoxMagnitudePopupMenuWillBecomeVisible
        carregarMagnitude();
    }//GEN-LAST:event_cBoxMagnitudePopupMenuWillBecomeVisible

    private void cBoxCentroCustoPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cBoxCentroCustoPopupMenuWillBecomeVisible
        carregarCentroCusto();
    }//GEN-LAST:event_cBoxCentroCustoPopupMenuWillBecomeVisible

    private void cBoxContaPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cBoxContaPopupMenuWillBecomeVisible
        carregarContaC();
    }//GEN-LAST:event_cBoxContaPopupMenuWillBecomeVisible

    private void listAnalisesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listAnalisesMouseClicked
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = ConexaoMySQL.getConexaoMySQL();
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("SELECT * FROM `analiseorcamento` WHERE `ID` = '"
                    + this.listAnalises.getSelectedValue() + "'");
            ResultSet rs = st.getResultSet();
            while (rs.next()) {
                jTextArea1.setText(rs.getString("ANALISE"));
                lAnalisePlataforma.setText(rs.getString("PLATAFORMA"));
                lAnaliseRegiao.setText(rs.getString("REGIAO"));
                lAnaliseFilial.setText(rs.getString("DESCRICAO_FILIAL"));
                lAnaliseMagnitude.setText(rs.getString("MAGNITUDE_CONTA"));
                lAnaliseCentro.setText(rs.getString("DESCRICAO_CC"));
                lAnaliseConta.setText(rs.getString("DESCRICAO_CONTA"));
                lOrcadoMes.setText(String.valueOf(rs.getDouble("BDG")));
                lRealMes.setText(String.valueOf(rs.getDouble("REALIZADO")));
                lOrcadoAcum.setText(String.valueOf(rs.getDouble("BDG_ACUM")));
                lRealAcum.setText(String.valueOf(rs.getDouble("REAL_ACUM")));
            }
            diferencaMes();
            ConexaoMySQL.FecharConexao();
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(rootPane, e);
            ConexaoMySQL.FecharConexao();
        }
    }//GEN-LAST:event_listAnalisesMouseClicked

    /**
     * @param args the command line arguments
     */
    public void carregarRegiao() {
        this.cBoxRegiao.removeAllItems();
        this.cBoxRegiao.addItem("");
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = ConexaoMySQL.getConexaoMySQL();
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("SELECT DISTINCT REGIAO FROM `analiseorcamento` WHERE `PLATAFORMA` LIKE '%"
                    + this.cBoxPlataforma.getSelectedItem() + "' AND `MES` LIKE '%"
                    + this.cBoxMes.getSelectedItem() + "' ORDER BY REGIAO");
            ResultSet rs = st.getResultSet();
            while (rs.next()) {
                cBoxRegiao.addItem(rs.getString("REGIAO"));
            }
            ConexaoMySQL.FecharConexao();
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(rootPane, e);
            ConexaoMySQL.FecharConexao();
        }
    }

    public void carregarFilial() {
        this.cBoxFilial.removeAllItems();
        this.cBoxFilial.removeItem("");
        this.cBoxFilial.addItem("");
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = ConexaoMySQL.getConexaoMySQL();
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("SELECT DISTINCT DESCRICAO_FILIAL FROM `analiseorcamento` WHERE `REGIAO` LIKE '%"
                    + this.cBoxRegiao.getSelectedItem() + "' AND `PLATAFORMA` LIKE '%"
                    + this.cBoxPlataforma.getSelectedItem() + "' AND `MES` LIKE '%"
                    + this.cBoxMes.getSelectedItem() + "' ORDER BY DESCRICAO_FILIAL");
            ResultSet rs = st.getResultSet();
            while (rs.next()) {
                cBoxFilial.addItem(rs.getString("DESCRICAO_FILIAL"));
            }
            ConexaoMySQL.FecharConexao();
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, e);
            ConexaoMySQL.FecharConexao();
        }
    }

    public void carregarMagnitude() {
        this.cBoxMagnitude.removeAllItems();
        this.cBoxMagnitude.removeItem("");
        this.cBoxMagnitude.addItem("");
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = ConexaoMySQL.getConexaoMySQL();
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("SELECT DISTINCT MAGNITUDE_CONTA FROM `analiseorcamento` WHERE `REGIAO` LIKE '%"
                    + this.cBoxRegiao.getSelectedItem() + "' AND `PLATAFORMA` LIKE '%"
                    + this.cBoxPlataforma.getSelectedItem() + "' AND `DESCRICAO_FILIAL` LIKE '%"
                    + this.cBoxFilial.getSelectedItem() + "' AND `MES` LIKE '%"
                    + this.cBoxMes.getSelectedItem() + "' ORDER BY MAGNITUDE_CONTA");
            ResultSet rs = st.getResultSet();
            while (rs.next()) {
                cBoxMagnitude.addItem(rs.getString("MAGNITUDE_CONTA"));
            }
            ConexaoMySQL.FecharConexao();
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, e);
            ConexaoMySQL.FecharConexao();
        }
    }

    public void carregarCentroCusto() {
        this.cBoxCentroCusto.removeAllItems();
        this.cBoxCentroCusto.removeItem("");
        this.cBoxCentroCusto.addItem("");
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = ConexaoMySQL.getConexaoMySQL();
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("SELECT DISTINCT CENTRO_DE_CUSTO FROM `analiseorcamento` WHERE `REGIAO` LIKE '%"
                    + this.cBoxRegiao.getSelectedItem() + "' AND `PLATAFORMA` LIKE '%"
                    + this.cBoxPlataforma.getSelectedItem() + "' AND `DESCRICAO_FILIAL` LIKE '%"
                    + this.cBoxFilial.getSelectedItem() + "' AND `MAGNITUDE_CONTA` LIKE '%"
                    + this.cBoxMagnitude.getSelectedItem() + "' AND `MES` LIKE '%"
                    + this.cBoxMes.getSelectedItem() + "' ORDER BY CENTRO_DE_CUSTO");
            ResultSet rs = st.getResultSet();
            while (rs.next()) {
                cBoxCentroCusto.addItem(rs.getString("CENTRO_DE_CUSTO"));
            }
            ConexaoMySQL.FecharConexao();
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, e);
            ConexaoMySQL.FecharConexao();
        }
    }

    public void carregarContaC() {
        this.cBoxConta.removeAllItems();
        this.cBoxConta.removeItem("");
        this.cBoxConta.addItem("");
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = ConexaoMySQL.getConexaoMySQL();
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("SELECT DISTINCT CONTA FROM `analiseorcamento` WHERE `REGIAO` LIKE '%"
                    + this.cBoxRegiao.getSelectedItem() + "' AND `PLATAFORMA` LIKE '%"
                    + this.cBoxPlataforma.getSelectedItem() + "' AND `DESCRICAO_FILIAL` LIKE '%"
                    + this.cBoxFilial.getSelectedItem() + "' AND `MAGNITUDE_CONTA` LIKE '%"
                    + this.cBoxMagnitude.getSelectedItem() + "' AND `CENTRO_DE_CUSTO` LIKE '%"
                    + this.cBoxCentroCusto.getSelectedItem() + "' AND `MES` LIKE '%"
                    + this.cBoxMes.getSelectedItem() + "' ORDER BY CONTA");
            ResultSet rs = st.getResultSet();
            while (rs.next()) {
                cBoxConta.addItem(rs.getString("CONTA"));
            }
            ConexaoMySQL.FecharConexao();
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, e);
            ConexaoMySQL.FecharConexao();
        }
    }

    public void limparParte() {
        if (("Operacional").equals(UsuarioLogado.perfil)) {

        } else if (("Supervisor").equals(UsuarioLogado.perfil)) {
            this.cBoxFilial.addItem("");
            this.cBoxMagnitude.addItem("");
        } else {
            this.cBoxRegiao.addItem("");
            this.cBoxFilial.addItem("");
        }
        this.cBoxMagnitude.addItem("");
        this.cBoxCentroCusto.addItem("");
        this.cBoxConta.addItem("");
        this.lID.setText("");
        this.jTextArea1.setText("");
        this.cBoxPlataforma.addItem("");
    }

    public void filtrarAnalise() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = ConexaoMySQL.getConexaoMySQL();
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("SELECT * FROM `analiseorcamento` WHERE `REGIAO` LIKE '%"
                    + this.cBoxRegiao.getSelectedItem() + "' AND `DESCRICAO_FILIAL` LIKE '%"
                    + this.cBoxFilial.getSelectedItem() + "' AND `MAGNITUDE_CONTA` LIKE '%"
                    + this.cBoxMagnitude.getSelectedItem() + "' AND `CENTRO_DE_CUSTO` LIKE '%"
                    + this.cBoxCentroCusto.getSelectedItem() + "' AND `CONTA` LIKE '%"
                    + this.cBoxConta.getSelectedItem() + "' AND `PLATAFORMA` LIKE '%"
                    + this.cBoxPlataforma.getSelectedItem() + "' AND `MES` LIKE '%"
                    + this.cBoxMes.getSelectedItem() + "' AND `BORR` LIKE '%"
                    + this.cBoxTipoOrcamento.getSelectedItem() + "' AND `TIPOJUS` LIKE '%"
                    + this.cBoxPreJustificativa.getSelectedItem() + "';");

            ResultSet rss = st.getResultSet();
            List analises = new ArrayList();
            if (rss.first()) {
                int teste = 1;
                analises.add(rss.getString("ID"));
                while (rss.next()) {
                    analises.add(rss.getString("ID"));
                    teste++;
                }
                this.listAnalises.setListData(analises.toArray());
                this.lNumeroAnalises.setText(String.valueOf(teste));
            } else {
                this.listAnalises.setListData(analises.toArray());
                this.lNumeroAnalises.setText(String.valueOf(0));
            }

            ConexaoMySQL.FecharConexao();
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(rootPane, e);
            ConexaoMySQL.FecharConexao();
        }
    }

    public void selmes() {
        DataHoje dh = new DataHoje();
        dh.Data();
        this.cBoxMes.setSelectedItem(dh.getDatahoje());
    }

    public void acesso() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = ConexaoMySQL.getConexaoMySQL();
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("SELECT * FROM `usuario` WHERE `USUARIO` LIKE '" + UsuarioLogado.usuario + "';");
            ResultSet rss = st.getResultSet();
            if (rss.first()) {
                if ("Operacional".equals(rss.getString("PERFIL"))) {
                    this.cBoxRegiao.setSelectedItem((String) rss.getString("REGIAO"));
                    this.cBoxFilial.setSelectedItem((String) rss.getString("FILIAL"));
                    this.cBoxRegiao.setEnabled(false);
                    this.cBoxFilial.setEnabled(false);
                } else if ("Administrador".equals(rss.getString("PERFIL"))) {
                } else if ("Supervisor".equals(rss.getString("PERFIL"))) {
                    this.cBoxRegiao.setSelectedItem((String) rss.getString("REGIAO"));
                    this.cBoxRegiao.setEnabled(false);
                } else if ("Observador".equals(rss.getString("PERFIL"))) {
                }
            } else {
                dispose();
            }
            ConexaoMySQL.FecharConexao();
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(rootPane, e);
            ConexaoMySQL.FecharConexao();
        }
    }

    public void diferencaMes() {
        Double realmes = (Double.parseDouble(this.lRealMes.getText()));
        Double bdgmes = (Double.parseDouble(this.lOrcadoMes.getText()));
        this.lDiferencaMes.setText(String.valueOf(bdgmes - realmes));
        Double realacum = (Double.parseDouble(this.lRealAcum.getText()));
        Double bdgacum = (Double.parseDouble(this.lOrcadoAcum.getText()));
        this.lDiferencaAcum.setText(String.valueOf(bdgacum - realacum));
    }

    public void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/br/com/controleorcamento/imagens/LDC_logo.png")));
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaliseConsulta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaliseConsulta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaliseConsulta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaliseConsulta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaliseConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bFiltrar;
    private javax.swing.JButton bLimpar;
    private javax.swing.JComboBox<Object> cBoxCentroCusto;
    private javax.swing.JComboBox<Object> cBoxConta;
    private javax.swing.JComboBox<String> cBoxFilial;
    private javax.swing.JComboBox<Object> cBoxMagnitude;
    private javax.swing.JComboBox<String> cBoxMes;
    private javax.swing.JComboBox<String> cBoxPlataforma;
    private javax.swing.JComboBox<Object> cBoxPreJustificativa;
    private javax.swing.JComboBox<String> cBoxRegiao;
    private javax.swing.JComboBox<String> cBoxTipoOrcamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lAnaliseCentro;
    private javax.swing.JLabel lAnaliseConta;
    private javax.swing.JLabel lAnaliseFilial;
    private javax.swing.JLabel lAnaliseMagnitude;
    private javax.swing.JLabel lAnalisePlataforma;
    private javax.swing.JLabel lAnaliseRegiao;
    private javax.swing.JLabel lCentroCusto1;
    private javax.swing.JLabel lCentroCusto2;
    private javax.swing.JLabel lDiferencaAcum;
    private javax.swing.JLabel lDiferencaMes;
    private javax.swing.JLabel lID;
    private javax.swing.JLabel lNumeroAnalises;
    private javax.swing.JLabel lOrcadoAcum;
    private javax.swing.JLabel lOrcadoMes;
    private javax.swing.JLabel lRealAcum;
    private javax.swing.JLabel lRealMes;
    private javax.swing.JList<Object> listAnalises;
    // End of variables declaration//GEN-END:variables

}
