/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.controleorcamento.formularios;

import br.com.controleorcamento.atividades.ConexaoMySQL;
import br.com.controleorcamento.atividades.InfracoesAtualizar;
import br.com.controleorcamento.atividades.InfracoesExcluir;
import br.com.controleorcamento.atividades.InfracoesSalvar;
import br.com.controleorcamento.objeto.Infracoes;
import java.awt.Toolkit;
import java.math.RoundingMode;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author rosaan
 */
public class CadastroInfracoes extends javax.swing.JFrame {

    /**
     * Creates new form CadastroUsuario
     */
    public CadastroInfracoes() {
        initComponents();
        carregarCondutor();
        carregarLocadora();
        carregarPlaca();
        filtrar();
        setIcon();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaInfracoes = new javax.swing.JTable();
        bSalvar = new javax.swing.JButton();
        bAtualizar = new javax.swing.JButton();
        bExcluir = new javax.swing.JButton();
        bFiltrar = new javax.swing.JButton();
        lID = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bLimpar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        tBoxCodigo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tBoxAutoInfracao = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tBoxNChamado = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        fTextPrazo = new javax.swing.JFormattedTextField();
        fTextDataInfracao = new javax.swing.JFormattedTextField();
        cBoxPlaca = new javax.swing.JComboBox<>();
        cBoxLocadora = new javax.swing.JComboBox<>();
        cBoxPontos = new javax.swing.JComboBox<>();
        lGravidade = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tBoxDescricaoMulta = new javax.swing.JTextArea();
        fTextValor = new javax.swing.JFormattedTextField();
        cBoxCondutor = new javax.swing.JComboBox<>();
        cBoxCondutorIdentificado = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lPontosMultas = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lValorMultas = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tAreaObs1 = new javax.swing.JTextArea();
        checkBoxReembolso = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/controleorcamento/imagens/icons8-Carro acidentado-16.png"))); // NOI18N
        jLabel1.setText("Cadastro de Infrações");

        jLabel2.setText("Placa");

        jLabel3.setText("Condutor Identificado");

        jLabel4.setText("Reembolso");

        jLabel5.setText("Gravidade");

        jLabel6.setText("Observação");

        jLabel8.setText("Locadora");

        tabelaInfracoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Placa", "Auto", "Locadora", "Gravidade", "Codigo", "Valor", "Prazo", "Condutor", "Pontos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaInfracoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaInfracoesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaInfracoes);
        if (tabelaInfracoes.getColumnModel().getColumnCount() > 0) {
            tabelaInfracoes.getColumnModel().getColumn(0).setPreferredWidth(30);
        }

        bSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/controleorcamento/imagens/icons8-Salvar-16.png"))); // NOI18N
        bSalvar.setText("Inserir");
        bSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvarActionPerformed(evt);
            }
        });

        bAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/controleorcamento/imagens/icons8-Atualizações disponíveis-16.png"))); // NOI18N
        bAtualizar.setText("Atualizar");
        bAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtualizarActionPerformed(evt);
            }
        });

        bExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/controleorcamento/imagens/icons8-Excluir-16.png"))); // NOI18N
        bExcluir.setText("Excluir");
        bExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExcluirActionPerformed(evt);
            }
        });

        bFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/controleorcamento/imagens/icons8-Filtro-16.png"))); // NOI18N
        bFiltrar.setText("Filtrar");
        bFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFiltrarActionPerformed(evt);
            }
        });

        jLabel9.setText("Pontos");

        bLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/controleorcamento/imagens/icons8-Vassoura-16.png"))); // NOI18N
        bLimpar.setText("Limpar");
        bLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimparActionPerformed(evt);
            }
        });

        jLabel11.setText("Cógigo");

        jLabel14.setText("Data");

        jLabel15.setText("Valor");

        jLabel16.setText("Auto de Infração");

        jLabel18.setText("Prazo para Recurso");

        jLabel21.setText("Condutor");

        jLabel22.setText("Nº do Chamado");

        try {
            fTextPrazo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fTextPrazo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fTextPrazoFocusGained(evt);
            }
        });

        try {
            fTextDataInfracao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fTextDataInfracao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fTextDataInfracaoFocusGained(evt);
            }
        });

        cBoxPontos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "3", "4", "5", "7" }));
        cBoxPontos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxPontosActionPerformed(evt);
            }
        });

        tBoxDescricaoMulta.setColumns(20);
        tBoxDescricaoMulta.setRows(5);
        jScrollPane2.setViewportView(tBoxDescricaoMulta);

        fTextValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        fTextValor.setText("0,00");
        fTextValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fTextValorFocusGained(evt);
            }
        });

        cBoxCondutorIdentificado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "C/ IDENTIFICAÇÃO", "S/ IDENTIFICAÇÃO", "C/ RECURSO" }));

        jLabel7.setText("Descrição Multa");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lPontosMultas.setText("Multas");

        jLabel13.setText("Pontos de Multas");

        lValorMultas.setText("Multas");

        jLabel10.setText("Valor de Multas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lPontosMultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lValorMultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lValorMultas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addGap(20, 20, 20))
                    .addComponent(lPontosMultas))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        tAreaObs1.setColumns(20);
        tAreaObs1.setRows(5);
        jScrollPane3.setViewportView(tAreaObs1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cBoxCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fTextPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tBoxAutoInfracao, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fTextValor, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fTextDataInfracao, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tBoxCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lGravidade, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cBoxPontos, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cBoxLocadora, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cBoxPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)))
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(135, 135, 135)
                                        .addComponent(tBoxNChamado, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(516, 516, 516)
                                            .addComponent(lID))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(3, 3, 3)))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(checkBoxReembolso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(cBoxCondutorIdentificado, 0, 188, Short.MAX_VALUE)))
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(22, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(lID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(cBoxPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(cBoxCondutorIdentificado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4)
                            .addComponent(cBoxLocadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkBoxReembolso))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cBoxPontos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lGravidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tBoxCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(fTextDataInfracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(fTextValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(tBoxAutoInfracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(fTextPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(cBoxCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(tBoxNChamado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bFiltrar)
                            .addComponent(bAtualizar)
                            .addComponent(bExcluir)
                            .addComponent(bSalvar)
                            .addComponent(bLimpar)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaInfracoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaInfracoesMouseClicked
        if (tabelaInfracoes.getSelectedRow() != -1) {
            lID.setText(tabelaInfracoes.getValueAt(tabelaInfracoes.getSelectedRow(), 0).toString());
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = ConexaoMySQL.getConexaoMySQL();
                java.sql.Statement st = conn.createStatement();
                st.executeQuery("SELECT * FROM `infracoes` WHERE `ID` = " + this.lID.getText());
                ResultSet rs = st.getResultSet();

                while (rs.next()) {
                    SimpleDateFormat fordata = new SimpleDateFormat("yyyy-MM-dd");
                    DecimalFormat df = new DecimalFormat("0.00");

                    try {
                        Date datainfra = fordata.parse((String) rs.getString("DATA"));
                        Date prazorec = fordata.parse((String) rs.getString("PRAZO_RECURSO"));
                        SimpleDateFormat forma = new SimpleDateFormat("dd/MM/yyyy");
                        String datainfrafor = (String) forma.format(datainfra);
                        String prazorecfotor = (String) forma.format(prazorec);

                        this.fTextPrazo.setValue(prazorecfotor);
                        this.fTextDataInfracao.setValue(datainfrafor);

                    } catch (ParseException ex) {
                        Logger.getLogger(CadastroInfracoes.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    this.cBoxPlaca.setSelectedItem(rs.getString("PLACA"));
                    this.cBoxLocadora.setSelectedItem(rs.getString("LOCADORA"));
                    this.cBoxPontos.setSelectedItem(rs.getString("PONTOS"));
                    this.lGravidade.setText(rs.getString("GRAVIDADE"));
                    this.tBoxCodigo.setText(rs.getString("CODIGO"));
                    this.tBoxDescricaoMulta.setText(rs.getString("DESCRICAO"));
                    this.fTextValor.setText(df.format(rs.getDouble("VALOR")));
                    this.tBoxAutoInfracao.setText(rs.getString("AUTO_DE_INFRACAO"));
                    this.cBoxCondutor.setSelectedItem(rs.getString("CONDUTOR"));
                    this.tBoxNChamado.setText(rs.getString("N_CHAMADO"));
                    this.cBoxCondutorIdentificado.setSelectedItem(rs.getString("CONDUTOR_IDENTIFICADO"));
                    this.tBoxDescricaoMulta.setText(rs.getString("OBSERVACAO"));

                    if (rs.getBoolean("REEMBOLSO") == false) {
                        this.checkBoxReembolso.setSelected(false);
                    } else {
                        this.checkBoxReembolso.setSelected(true);
                    }
                }
                ConexaoMySQL.FecharConexao();
            } catch (SQLException | ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, e);
                ConexaoMySQL.FecharConexao();
            }
        }
    }//GEN-LAST:event_tabelaInfracoesMouseClicked

    private void bFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFiltrarActionPerformed
        filtrar();
    }//GEN-LAST:event_bFiltrarActionPerformed

    private void bAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtualizarActionPerformed
        Infracoes infra = new Infracoes();
        InfracoesAtualizar infraatu = new InfracoesAtualizar();
        SimpleDateFormat fordata = new SimpleDateFormat("dd/MM/yyyy");
        try {
            Date datainfra = fordata.parse((String) this.fTextDataInfracao.getText());
            Date prazorec = fordata.parse((String) this.fTextPrazo.getText());
            SimpleDateFormat forma = new SimpleDateFormat("yyyy-MM-dd");
            String datainfrafor = (String) forma.format(datainfra);
            String prazorecfor = (String) forma.format(prazorec);
            infra.setData(datainfrafor);
            infra.setPrazorecurso(prazorecfor);

        } catch (ParseException ex) {
            Logger.getLogger(CadastroInfracoes.class.getName()).log(Level.SEVERE, null, ex);
        }
        String valortransformado = ((String) this.fTextValor.getText());
        valortransformado = valortransformado.replace(".", "");
        valortransformado = valortransformado.replace(",", ".");

        infra.setId(Integer.parseInt(lID.getText()));
        infra.setPlaca((String) cBoxPlaca.getSelectedItem());
        infra.setLocadora((String) cBoxLocadora.getSelectedItem());
        infra.setPonto(Integer.parseInt((String) cBoxPontos.getSelectedItem()));
        infra.setGravidade(lGravidade.getText());
        infra.setCodigo(tBoxCodigo.getText());
        infra.setDescricao(tBoxDescricaoMulta.getText());
        infra.setValor(Double.parseDouble(valortransformado));
        infra.setAutoinfra(tBoxAutoInfracao.getText());
        infra.setCondutor((String) cBoxCondutor.getSelectedItem());
        infra.setNchamado(tBoxNChamado.getText());
        infra.setCondutoridentificado((String) cBoxCondutorIdentificado.getSelectedItem());
        infra.setObs(tBoxDescricaoMulta.getText());

        if (this.checkBoxReembolso.isSelected()) {
            infra.setReembolso(true);
        } else {
            infra.setReembolso(false);
        }

        infraatu.InfracoesAtualizar(infra);
        limpar();
        filtrar();
        JOptionPane.showMessageDialog(this, "Infração atualizada com sucesso");
    }//GEN-LAST:event_bAtualizarActionPerformed

    private void bSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvarActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = ConexaoMySQL.getConexaoMySQL();
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("SELECT AUTO_DE_INFRACAO FROM `infracoes` WHERE `AUTO_DE_INFRACAO` LIKE '" + this.tBoxAutoInfracao.getText() + "'");
            ResultSet rs = st.getResultSet();
            if (rs.first()) {
                JOptionPane.showMessageDialog(this, "Auto de infração já cadastrado");
                return;
            }
            Infracoes infra = new Infracoes();
            InfracoesSalvar infrasalv = new InfracoesSalvar();
            SimpleDateFormat fordata = new SimpleDateFormat("dd/MM/yyyy");
            try {
                Date datainfra = fordata.parse((String) this.fTextDataInfracao.getText());
                Date prazorec = fordata.parse((String) this.fTextPrazo.getText());
                SimpleDateFormat forma = new SimpleDateFormat("yyyy-MM-dd");
                String datainfrafor = (String) forma.format(datainfra);
                String prazorecfor = (String) forma.format(prazorec);
                infra.setData(datainfrafor);
                infra.setPrazorecurso(prazorecfor);
            } catch (ParseException ex) {
                Logger.getLogger(CadastroInfracoes.class.getName()).log(Level.SEVERE, null, ex);
            }
            String valortransformado = ((String) this.fTextValor.getText());
            valortransformado = valortransformado.replace(".", "");
            valortransformado = valortransformado.replace(",", ".");

            infra.setPlaca((String) cBoxPlaca.getSelectedItem());
            infra.setLocadora((String) cBoxLocadora.getSelectedItem());
            infra.setPonto(Integer.parseInt((String) cBoxPontos.getSelectedItem()));
            infra.setGravidade(lGravidade.getText());
            infra.setCodigo(tBoxCodigo.getText());
            infra.setDescricao(tBoxDescricaoMulta.getText());
            infra.setValor(Double.parseDouble(valortransformado));
            infra.setAutoinfra(tBoxAutoInfracao.getText());
            infra.setCondutor((String) cBoxCondutor.getSelectedItem());
            infra.setNchamado(tBoxNChamado.getText());
            infra.setCondutoridentificado((String) cBoxCondutorIdentificado.getSelectedItem());
//            infra.setReembolso(tBoxReembolso.getText());
            infra.setObs(tBoxDescricaoMulta.getText());

            if (this.checkBoxReembolso.isSelected()) {
                infra.setReembolso(true);
            } else {
                infra.setReembolso(false);
            }

            infrasalv.InfracoesSalvar(infra);
            limpar();
            filtrar();
            JOptionPane.showMessageDialog(this, "Infração cadastrada com sucesso");
            ConexaoMySQL.FecharConexao();
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(rootPane, e);
            ConexaoMySQL.FecharConexao();
        }


    }//GEN-LAST:event_bSalvarActionPerformed

    private void bExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExcluirActionPerformed
        if (lID.getText() == "") {
            JOptionPane.showMessageDialog(this, "Selecione uma infração clicando na tabela");
            return;
        }
        Infracoes infra = new Infracoes();
        InfracoesExcluir infraexc = new InfracoesExcluir();

        infra.setId(Integer.parseInt(lID.getText()));

        infraexc.InfracoesExcluir(infra);
        limpar();
        filtrar();
        JOptionPane.showMessageDialog(this, "Infração excluída com sucesso");
    }//GEN-LAST:event_bExcluirActionPerformed

    private void bLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimparActionPerformed
        limpar();
        filtrar();
    }//GEN-LAST:event_bLimparActionPerformed

    private void fTextPrazoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fTextPrazoFocusGained
        this.fTextPrazo.setText("");
    }//GEN-LAST:event_fTextPrazoFocusGained

    private void fTextDataInfracaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fTextDataInfracaoFocusGained
        this.fTextDataInfracao.setText("");
    }//GEN-LAST:event_fTextDataInfracaoFocusGained

    private void fTextValorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fTextValorFocusGained
        this.fTextValor.setText("");
    }//GEN-LAST:event_fTextValorFocusGained

    private void cBoxPontosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxPontosActionPerformed
        if ("3" == this.cBoxPontos.getSelectedItem()) {
            this.lGravidade.setText("LEVE");
        } else if ("4" == this.cBoxPontos.getSelectedItem()) {
            this.lGravidade.setText("MÉDIA");
        } else if ("5" == this.cBoxPontos.getSelectedItem()) {
            this.lGravidade.setText("GRAVE");
        } else if ("7" == this.cBoxPontos.getSelectedItem()) {
            this.lGravidade.setText("GRAVÍSSIMA");
        }
    }//GEN-LAST:event_cBoxPontosActionPerformed

    /**
     * @param args the command line arguments
     */
    public void filtrar() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaInfracoes.getModel();
        tabelaInfracoes.setRowSorter(new TableRowSorter(modelo));
        modelo.setNumRows(0);
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = ConexaoMySQL.getConexaoMySQL();
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("SELECT * FROM `infracoes` WHERE `PLACA` LIKE '%"
                    + this.cBoxPlaca.getSelectedItem() + "%' AND `LOCADORA` LIKE '%"
                    + this.cBoxLocadora.getSelectedItem() + "%' AND `GRAVIDADE` LIKE '%"
                    + this.lGravidade.getText() + "%' AND `CODIGO` LIKE '%"
                    + this.tBoxCodigo.getText() + "%' AND `AUTO_DE_INFRACAO` LIKE '%"
                    + this.tBoxAutoInfracao.getText() + "%' AND `CONDUTOR` LIKE '%"
                    + this.cBoxCondutor.getSelectedItem() + "%' AND `N_CHAMADO` LIKE '%"
                    + this.tBoxNChamado.getText() + "%' AND `CONDUTOR_IDENTIFICADO` LIKE '%"
                    + this.cBoxCondutorIdentificado.getSelectedItem() + "%' ORDER BY `CONDUTOR`");
            ResultSet rs = st.getResultSet();

            while (rs.next()) {
                SimpleDateFormat formatado = new SimpleDateFormat("dd/MM/yyyy");
                String prazo = formatado.format(rs.getDate("PRAZO_RECURSO"));

                modelo.addRow(new Object[]{
                    rs.getInt("ID"),
                    rs.getString("PLACA"),
                    rs.getString("AUTO_DE_INFRACAO"),
                    rs.getString("LOCADORA"),
                    rs.getString("GRAVIDADE"),
                    rs.getString("CODIGO"),
                    rs.getDouble("VALOR"),
                    prazo,
                    rs.getString("CONDUTOR"),
                    rs.getInt("PONTOS"),});
            }
            somarValoresdaTabela();
            ConexaoMySQL.FecharConexao();

        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(rootPane, e);
            ConexaoMySQL.FecharConexao();
        }
    }

    public void limpar() {
        this.cBoxPlaca.setSelectedItem("");
        this.cBoxLocadora.setSelectedItem("");
        this.cBoxPontos.setSelectedItem("");
        this.tBoxCodigo.setText("");
        this.fTextDataInfracao.setText("");
        this.fTextValor.setText("0");
        this.tBoxAutoInfracao.setText("");
        this.fTextPrazo.setText("");
        this.cBoxCondutor.setSelectedItem("");
        this.tBoxNChamado.setText("");
        this.cBoxCondutorIdentificado.setSelectedItem("");
        this.checkBoxReembolso.setSelected(false);
        this.tBoxDescricaoMulta.setText("");
        this.tBoxDescricaoMulta.setText("");
    }

    public void carregarPlaca() {
        this.cBoxPlaca.removeAllItems();
        this.cBoxPlaca.addItem("");
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = ConexaoMySQL.getConexaoMySQL();
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("SELECT DISTINCT PLACA FROM `veiculos` ORDER BY PLACA");
            ResultSet rs = st.getResultSet();
            while (rs.next()) {
                cBoxPlaca.addItem(rs.getString("PLACA"));
            }
            ConexaoMySQL.FecharConexao();
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(rootPane, e);
            ConexaoMySQL.FecharConexao();
        }
    }

    public void carregarLocadora() {
        this.cBoxLocadora.removeAllItems();
        this.cBoxLocadora.addItem("");
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = ConexaoMySQL.getConexaoMySQL();
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("SELECT DISTINCT LOCADOR FROM `veiculos` ORDER BY LOCADOR");
            ResultSet rs = st.getResultSet();
            while (rs.next()) {
                cBoxLocadora.addItem(rs.getString("LOCADOR"));
            }
            ConexaoMySQL.FecharConexao();
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(rootPane, e);
            ConexaoMySQL.FecharConexao();
        }
    }

    public void carregarCondutor() {
        this.cBoxCondutor.removeAllItems();
        this.cBoxCondutor.addItem("");
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = ConexaoMySQL.getConexaoMySQL();
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("SELECT DISTINCT NOME FROM `condutor` ORDER BY NOME");
            ResultSet rs = st.getResultSet();
            while (rs.next()) {
                cBoxCondutor.addItem(rs.getString("NOME"));
            }
            ConexaoMySQL.FecharConexao();
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(rootPane, e);
            ConexaoMySQL.FecharConexao();
        }
    }

    public void somarValoresdaTabela() {
        DecimalFormat df = new DecimalFormat("###,###,###,###.##");
        df.setRoundingMode(RoundingMode.UP);

        double somamultas = 0;
        double somapontos = 0;
        for (int i = 0; i <= tabelaInfracoes.getRowCount() - 1; i++) {
            somamultas += Double.parseDouble(tabelaInfracoes.getValueAt(i, 6).toString());
            somapontos += Double.parseDouble(tabelaInfracoes.getValueAt(i, 9).toString());
        }
        lValorMultas.setText(String.valueOf(df.format(somamultas)));
        lPontosMultas.setText(String.valueOf(df.format(somapontos)));
    }

    public void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/br/com/controleorcamento/imagens/LDC_logo.png")));
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroInfracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroInfracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroInfracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroInfracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroInfracoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAtualizar;
    private javax.swing.JButton bExcluir;
    private javax.swing.JButton bFiltrar;
    private javax.swing.JButton bLimpar;
    private javax.swing.JButton bSalvar;
    private javax.swing.JComboBox<Object> cBoxCondutor;
    private javax.swing.JComboBox<Object> cBoxCondutorIdentificado;
    private javax.swing.JComboBox<Object> cBoxLocadora;
    private javax.swing.JComboBox<Object> cBoxPlaca;
    private javax.swing.JComboBox<Object> cBoxPontos;
    private javax.swing.JCheckBox checkBoxReembolso;
    private javax.swing.JFormattedTextField fTextDataInfracao;
    private javax.swing.JFormattedTextField fTextPrazo;
    private javax.swing.JFormattedTextField fTextValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lGravidade;
    private javax.swing.JLabel lID;
    private javax.swing.JLabel lPontosMultas;
    private javax.swing.JLabel lValorMultas;
    private javax.swing.JTextArea tAreaObs1;
    private javax.swing.JTextField tBoxAutoInfracao;
    private javax.swing.JTextField tBoxCodigo;
    private javax.swing.JTextArea tBoxDescricaoMulta;
    private javax.swing.JTextField tBoxNChamado;
    private javax.swing.JTable tabelaInfracoes;
    // End of variables declaration//GEN-END:variables
}
